import Head from "next/head";
import Header from "../components/layouts/Header";
import Hero01 from "../components/home/Hero01";
import Hero02 from "../components/home/Hero02";
import Security from "../components/home/Security";
import Pricing from "../components/home/Pricing";
import Testimonials from "../components/home/Testimonials";
import Contect from "../components/home/Contact";
import Faq from "../components/home/Faq";
import CallToAction from "../components/home/CallToAction";
import Footer from "../components/layouts/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Header />
      <Hero01 />
      <Hero02 />
      <Security />
      <Pricing />
      <Testimonials />
      <Contect />
      <Faq />
      <CallToAction />
      <Footer />
    </>
  );
}
